[package]
name = "inori"
version = "0.3.0"
edition = "2021"
rust-version = "1.82"
authors = ["esrh <esrh@esrh.me>"]
description = "mpd client"
homepage = "https://github.com/eshrh/inori"
repository = "https://github.com/eshrh/inori"
license = "GPL-3.0-only"
readme = "README.md"
keywords = ["mpd", "music"]
categories = ["command-line-utilities", "multimedia", "multimedia::audio"]

[lints.rust]
unsafe_code = "forbid"

[dependencies]
ratatui = { version = "0.30.0", features = ["serde"] }
nucleo-matcher = "0.3.1"
itertools = "0.14.0"
bitflags = "2.11.0"
toml = "1.0.4"
platform-dirs = "0.3.0"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }

[dependencies.mpd]
version = "0.2.3"
package = "inori-mpd"
